# -*- coding: utf-8 -*-
"""SMIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KrrhhxcDUbxxm_1ROc3XtnVtVR6lKdP5
"""

!git clone https://github.com/Seanseattle/SMIS.git

# Commented out IPython magic to ensure Python compatibility.

# %cd SMIS

!gdown 1ckx35-mlMv57yzv47bmOCrWTm5l2X-zD

!tar -xvf /content/SMIS/deepfashion.tar

!pip install torch torchvision dominate dill scikit-image tqdm opencv-python

!gdown 1og_9By_xdtnEd9-xawAj4jYbXR6A9deG

!unrar e /content/SMIS/smis_pretrained.rar

!ls

!chmod +x ./scripts/deepfashion.sh

!pip install torch

! ./scripts/deepfashion.sh --gpu_ids 0

!nvidia-smi

!ls

!python3 test.py --name deepfashion_smis --dataset_mode deepfashion --dataroot ./ --no_instance  --gpu_ids 0 --ngf 160 --batchSize 4 --model smis --netG deepfashion

